name: coffee_app
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.2


  # Correct package for Advanced Drawer
  flutter_advanced_drawer: ^1.3.5

  # Icons for iOS-style apps
  cupertino_icons: ^1.0.8

  # Lottie dependency for animations
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^4.0.0

flutter:
  # Enables Material Design icons
  uses-material-design: true
